# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
# use_frameworks!

inhibit_all_warnings!

pod 'AFNetworking', '~> 3.0'
pod 'ViperMcFlurry', '~> 1.2'
pod 'Masonry', '~> 0.6'
pod 'pop', '~> 1.0'
